include:
  # import Kafka internal :
  - ./kafka-ssl/docker-compose-qa.yml
  # import Kafka external :
  - ./kafka-avro/docker-compose.yml
services:
  postgres:
    image: postgres:17.8-alpine
    container_name: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${PG_DB_USERNAME}
      - POSTGRES_PASSWORD=${PG_DB_PASSWORD}
    volumes:
    # Use commands for Linux, because I'm gonna use Linux OS for AWS hosting
    # Note: "$(pwd)/" and "./" - just two possible options to do the same things
    # 1. To back up the current data state :
      - $(pwd)/postgres/backup:/var/lib/postgresql/data
    # 2. To initialize multiple databases before DB starting :
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_DB_USERNAME} -d ${PG_BD-1} && pg_isready -U ${PG_DB_USERNAME} -d ${PG_BD-2}" ]
      interval: 5s
      retries: 5
      start_period: 25s
      timeout: 5s
  redis:
    image: redis
    container_name: 'redis'
    ports:
      - '6379:6379'
  notification-gateway-service:
    image: '"${DOCKER_ID}"/notification-gateway-service-boot'
    container_name: 'notification-gateway-service'
    ports:
      - '8180:8180'
    depends_on:
      - 'kafka-internal'
    environment:
      - KAFKA_BROKER_HOST=${INTERNAL_KAFKA_BROKER_HOST}
  auth-service:
    image: '"${DOCKER_ID}"/auth-service-boot'
    container_name: 'auth-service'
    ports:
      - '8100:8100'
      - '5015:5005'
    depends_on:
      - 'kafka-internal'
      - 'notification-gateway-service'
    environment:
      - SPRING_PROFILES_ACTIVE=qa
      - KAFKA_BROKER_HOST=${INTERNAL_KAFKA_BROKER_HOST}
      - MONGO_DB_PASSWORD
  profile-service:
    image: "${DOCKER_ID}"/profile-service-boot
    container_name: profile-service
    ports:
      - 8200:8200
      - 5025:5005
    depends_on:
      - auth-service
      - kafka-external
      - schema-registry
    environment:
      - SPRING_PROFILES_ACTIVE=qa
      - MONGO_DB_PASSWORD
      - AUTH_SERVICE_HOST=auth-service
      - KAFKA_BROKER_HOST=${EXTERNAL_KAFKA_BROKER_HOST}
      - KAFKA_SCHEMA_REGISTRY_HOST=${EXTERNAL_KAFKA_SCHEMA_REGISTRY_HOST}
#  profile-soap-service:
#    image: '"${DOCKER_ID}"/profile-soap-service-boot'
#    container_name: 'profile-soap-service'
#    ports:
#      - '8250:8250'
#      - '5225:5005'
#    depends_on:
#      - 'auth-service'
#      - 'kafka-external'
#      - 'schema-registry'
#    environment:
#      - MONGO_DB_PASSWORD
#      - AUTH_SERVICE_HOST=auth-service
#      - KAFKA_BROKER_HOST=${EXTERNAL_KAFKA_BROKER_HOST}
#      - KAFKA_SCHEMA_REGISTRY_HOST=${EXTERNAL_KAFKA_SCHEMA_REGISTRY_HOST}
  order-service:
    image: '"${DOCKER_ID}"/order-service-boot'
    container_name: 'order-service'
    ports:
      - '8300:8300'
      - '5035:5005'
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      kafka-internal:
        condition: service_started
      auth-service:
        condition: service_started
      profile-service:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=qa
      - MONGO_DB_PASSWORD
      - PG_HOST=${PG_DB_HOST}
      - PG_USERNAME=${PG_DB_USERNAME}
      - PG_PASSWORD=${PG_DB_PASSWORD}
      # It must be internal Port and Name of containers:
      - kafka.bootstrapServers=${INTERNAL_KAFKA_BROKER_HOST}:9092
#      - kafka.ssl-keystore-location=/app/clientkeystore.jks
#      - kafka.ssl-truststore-location=/app/clienttruststore.jks
#      - datasource.api.jdbc-url=jdbc:postgresql://postgres:5432/apiDB
#      - auth-rest-client.url=http://auth-service:8100
#      - profile-rest-client.url=http://profile-service:8200
  event-storage-service:
    image: '"${DOCKER_ID}"/event-storage-service-boot'
    container_name: 'event-storage-service'
    ports:
      - '8400:8400'
      - '5045:5005'
    depends_on:
      - 'auth-service'
      - 'order-service'
      - 'kafka-internal'
    environment:
      - SPRING_PROFILES_ACTIVE=qa
      - MONGO_DB_PASSWORD
      - kafka.bootstrapServers=${INTERNAL_KAFKA_BROKER_HOST}:9092
#      - kafka.ssl-keystore-location=/app/clientkeystore.jks
#      - kafka.ssl-truststore-location=/app/clienttruststore.jks
  message-chat-service:
    image: '"${DOCKER_ID}"/message-chat-service-boot'
    container_name: 'message-chat-service'
    ports:
      - '8500:8500'
      - '5055:5005'
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
      auth-service:
        condition: service_started
      profile-service:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=qa
      - PG_HOST=${PG_DB_HOST}
      - PG_USERNAME=${PG_DB_USERNAME}
      - PG_PASSWORD=${PG_DB_PASSWORD}
      - TRANSLATE_API_TOKEN
      - profile-rest-client.url=http://profile-service:8200
      - REDIS_HOST=redis
  nginx:
    image: nginx
    container_name: 'nginx-revers-proxy'
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - 'auth-service'
      - 'profile-service'
      - 'order-service'
      - 'event-storage-service'
      - 'message-chat-service'
#  task-executor-service:
#    image: '"${DOCKER_ID}"/task-executor-service-boot'
#    container_name: 'task-executor-service'
#    ports:
#      - '8600:8600'
#      - '5065:5005'
#    depends_on:
#      - 'auth-service'
#      - 'profile-service'
#      - 'kafka-external'
#      - 'schema-registry'
#    environment:
#      - SPRING_PROFILES_ACTIVE=qa
#      - MONGO_DB_PASSWORD
#      - PROFILE_SERVICE_HOST=profile-service
#      - KAFKA_BROKER_HOST=${EXTERNAL_KAFKA_BROKER_HOST}
#      - KAFKA_SCHEMA_REGISTRY_HOST=${EXTERNAL_KAFKA_SCHEMA_REGISTRY_HOST}