server {
  listen 80;
  location /api/auth-service/ {
    proxy_pass http://auth-service:8100;
    proxy_set_header x-lang $http_x_lang;
    proxy_set_header X-Real-IP $remote_addr;
  }
  location /api/profile-service/ {
    proxy_pass http://profile-service:8200;
    proxy_set_header x-lang $http_x_lang;
    proxy_set_header X-Real-IP $remote_addr;
  }
  location /api/order-service/ {
    proxy_pass http://order-service:8300;
    proxy_set_header x-lang $http_x_lang;
    proxy_set_header X-Real-IP $remote_addr;
  }
  location /api/event-storage-service/ {
    proxy_pass http://event-storage-service:8400;
    proxy_set_header x-lang $http_x_lang;
    proxy_set_header X-Real-IP $remote_addr;
  }
  location /api/massages-chat-service/ {
    proxy_pass http://message-chat-service:8500;
    proxy_set_header x-lang $http_x_lang;
    proxy_set_header X-Real-IP $remote_addr;
  }
}