server:
  port: 8500

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:${MONGO_DB_PASSWORD}@cluster0.lme5y.mongodb.net/mutual-aid-app?retryWrites=true&w=majority
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

application:
  api-info:
    version: 2.0
    title: MESSAGE CHAT
    description: Message chat SERVICE
    contact:
      name: OLEG
      url: https://mail.google.com
      email: vilchinskioleg@gmail.com

feign:
  client:
    config:
      profileRestClient:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
#        requestInterceptors:
#          - com.example.FooRequestInterceptor
      googleTranslateApiClient:
        connectTimeout: 10000
        readTimeout: 15000
        loggerLevel: full
  okhttp:
    enabled: true

google-translate-open-api:
  url: https://google-translate1.p.rapidapi.com/language/translate/v2
  host: google-translate1.p.rapidapi.com
  token: ${TRANSLATE_API_TOKEN}
  encoding: application/gzip

profile-rest-client:
  url: http://localhost:8200
  user: message-chat-service-client
  password:

message-chat-properties:
  translation-message:
    enabled: true