server:
  port: 8500

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    # something like 'non_null' included in 'non_empty' prop-value:
    default-property-inclusion: non_empty
    parser:
      allow-comments: true

application:
  api-info:
    version: 2.0
    title: MESSAGE CHAT
    description: Message chat SERVICE
    contact:
      name: OLEG
      url: https://mail.google.com
      email: vilchinskioleg@gmail.com

datasource:
  message-chat:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/messageChatService
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

feign:
  client:
    config:
      profileRestClient:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
        requestInterceptors:
          - messagechat.messagechatservice.configuration.client.profile.ProfileRestClientAuthInterceptor
      googleTranslateApiClient:
        connectTimeout: 10000
        readTimeout: 15000
        loggerLevel: full
  okhttp:
    enabled: true

google-translate-open-api:
  url: https://google-translate1.p.rapidapi.com/language/translate/v2
  host: google-translate1.p.rapidapi.com
  token: ${TRANSLATE_API_TOKEN}
  encoding: application/gzip

profile-rest-client:
  username: message-chat-service-client

logging:
  level:
    root: info