spring:
  data:
    mongodb:
      database: mutual-aid-app
      uri: mongodb://localhost:27017/mutual-aid-app

application:
  api-info:
    version: 2.0
    title: MESSAGE CHAT
    description: Message chat SERVICE
    contact:
      name: OLEG
      url: https://mail.google.com
      email: vilchinskioleg@gmail.com

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 50000
        loggerLevel: full
  okhttp:
    enabled: true

google-translate-open-api:
  url: https://google-translate1.p.rapidapi.com/language/translate/v2
  host: google-translate1.p.rapidapi.com
  token: xxx
  encoding: application/gzip

message-chat-properties:
  translation-message:
    enabled: true