spring:
  liquibase:
    enabled: true

profile-rest-client:
  url: http://localhost:8200
  password: 42voRTvk_wEle!76

message-chat-properties:
  translation-message:
    enabled: true

jpa-props:
  message-chat:
    ddl-auto: none