spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:${MONGO_DB_PASSWORD}@cluster0.lme5y.mongodb.net/mutual-aid-app?retryWrites=true&w=majority

profile-rest-client:
  url: http://localhost:8200
  password: 42voRTvk_wEle!76

message-chat-properties:
  translation-message:
    enabled: true