server:
  port: 8180

spring:
  application:
    name: notification-gateway
  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE
      concurrency: 5 # defined here because there is single consumer
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: false
      max-poll-records: 10
      group-id: notification-gateway
      properties:
        max.poll.interval.ms: 600000  # 10 minutes
  mail:
    host: smtp.gmail.com
    port: 587
    username: vin76423@gmail.com
    password: cqva clql lbuw zamk
    properties:
      mail:
#        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
#          connectiontimeout: 5000
#          writetimeout: 5000
#          timeout: 5000
          starttls:
            enable: true

notification-gateway:
  kafka:
    topic: mutual-aid-notification-topic