feign:
  client:
    config:
      authRestClient:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
  #        requestInterceptors:
  #          - com.example.FooRequestInterceptor
  httpclient:
    enabled: true

auth-rest-client:
  url: http://localhost:8800/api/auth-service
  read-timeout: 10000
  connection-timeout: 10000

basic-clients:
  - test:
      name: test
      password: 123
      rules:
        - asdsfds
        - sdff
  - super:
      name: super
        password: 12345
        rules:
          - asdsfds