version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zoo1
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: broker1
    ports:
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181

      KAFKA_LISTENERS: SSL://broker1:9093
      KAFKA_ADVERTISED_LISTENERS: SSL://broker1:9093

      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      SSL_ENABLED_PROTOCOLS: 'TLSv1,TLSv1.1,TLSv1.2,TLSv1.3'
      KAFKA_SSL_CLIENT_AUTH: 'required'

      KAFKA_SSL_KEY_PASSWORD: '34rtsTb290'
      KAFKA_SSL_KEYSTORE_LOCATION: '/etc/kafka/secrets/certs/serverkeystore.jks'
      KAFKA_SSL_KEYSTORE_PASSWORD: '34rtsTb290'
      KAFKA_SSL_TRUSTSTORE_LOCATION: '/etc/kafka/secrets/certs/servertruststore.jks'
      KAFKA_SSL_TRUSTSTORE_PASSWORD: '34rtsTb290'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./secret/broker/serverkeystore.jks:/etc/kafka/secrets/certs/serverkeystore.jks
      - ./secret/broker/servertruststore.jks:/etc/kafka/secrets/certs/servertruststore.jks