version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: 'zookeeper'
    hostname: zookeeper
    ports:
      - '2181:2181'
  kafka:
#    image: wurstmeister/kafka
    build:
      dockerfile: Dockerfile.Kafka.SSL
      context: .
    container_name: 'kafka'
    hostname: 'kafka'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: SSL://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: SSL://kafka:9092
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      SSL_ENABLED_PROTOCOLS: 'TLSv1,TLSv1.1,TLSv1.2,TLSv1.3'
      KAFKA_SSL_CLIENT_AUTH: 'required'
      KAFKA_SSL_KEY_PASSWORD: '34rtsTb290'
      KAFKA_SSL_KEYSTORE_LOCATION: '/serverkeystore.jks'
      KAFKA_SSL_KEYSTORE_PASSWORD: '34rtsTb290'
      KAFKA_SSL_TRUSTSTORE_LOCATION: '/servertruststore.jks'
      KAFKA_SSL_TRUSTSTORE_PASSWORD: '34rtsTb290'