services:
    zookeeper-internal:
      image: 'wurstmeister/zookeeper'
      container_name: 'zookeeper-internal'
      hostname: 'zookeeper'
      ports:
        - '2181:2181'
    kafka-internal:
      build:
        dockerfile: Dockerfile.Kafka.SSL
        context: .
      image: 'kafka-ssl'
      container_name: 'kafka-internal'
      hostname: 'kafka'
      ports:
        - '9092:9092'
      depends_on:
        - 'zookeeper-internal'
      environment:
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENERS: SSL://${INTERNAL_KAFKA_BROKER_HOST}:9092
        KAFKA_ADVERTISED_LISTENERS: SSL://${INTERNAL_KAFKA_BROKER_HOST}:9092
        # I explicitly defined protocol for communicate broker between each other:
        # I have to define it and change default value (PLAINTEXT) because I didn't define any PLAINTEXT listeners before.
        KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
        SSL_ENABLED_PROTOCOLS: 'TLSv1,TLSv1.1,TLSv1.2,TLSv1.3'
        KAFKA_SSL_CLIENT_AUTH: 'required'
        KAFKA_SSL_KEY_PASSWORD: '34rtsTb290'
        KAFKA_SSL_KEYSTORE_LOCATION: '/serverkeystore.jks'
        KAFKA_SSL_KEYSTORE_PASSWORD: '34rtsTb290'
        KAFKA_SSL_TRUSTSTORE_LOCATION: '/servertruststore.jks'
        KAFKA_SSL_TRUSTSTORE_PASSWORD: '34rtsTb290'