# Only as example to run application with local DB:

version: '3'
services:
  order-service:
    build: .
    image: 'order-service-img'
    container_name: 'order-service'
    ports:
      - '8300:8300'
      - '5005:5005'
    environment:
      - MONGO_HOST=mongo-db
      - MONGO_PORT=27017
      - MONGO_DB=mutual-aid-app_MOCK
      - MONGO_USERNAME=testUser
      - MONGO_PWD=welcome!
    links:
      - mongo-db
  mongo-db:
    image: 'mongo:5.0.5'
    container_name: 'mongo-db'
    ports:
      - '27017:27017'
    volumes:
      - ./init-mongodb:/docker-entrypoint-initdb.d
      - ./init-mongodb/data:/tmp/data