server {
  listen 80;
  location /api/auth-service/ {
    # 1. Define the backend server address :
    proxy_pass http://auth-service:8100;

    # 2. Set Standard Headers (Recommended for all proxy configurations)
    # These headers ensure the backend knows the client's actual IP and host.
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # 3. Explicitly forward the Authorization header
    proxy_set_header Authorization $http_authorization;
    proxy_set_header x-lang $http_x_lang;
  }
  location /api/profile-service/ {
    proxy_pass http://profile-service:8200;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_set_header Authorization $http_authorization;
    proxy_set_header x-lang $http_x_lang;
  }
  location /api/order-service/ {
    proxy_pass http://order-service:8300;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_set_header Authorization $http_authorization;
    proxy_set_header x-lang $http_x_lang;
  }
  location /api/event-storage-service/ {
    proxy_pass http://event-storage-service:8400;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_set_header Authorization $http_authorization;
    proxy_set_header x-lang $http_x_lang;
  }
  location /api/massages-chat-service/ {
    proxy_pass http://message-chat-service:8500;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_set_header Authorization $http_authorization;
    proxy_set_header x-lang $http_x_lang;
  }
}