apiVersion: v1
kind: Pod
metadata:
  name: auth-service-pod
  labels:
    component: auth
spec:
  containers:
    - name: auth-service-container
      image: alehvilchynski/auth-service-boot
      ports:
        - containerPort: 8100