spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:${MONGO_DB_PASSWORD:test}@cluster0.lme5y.mongodb.net/mutual-aid-app?retryWrites=true&w=majority&appName=Cluster0

profile-rest-client:
  password:

logging:
  level:
    root: warn
    org.tms.task_executor_service.domain.service.kafka.consumer.TaskForRetryingListener: warn