spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:${MONGO_DB_PASSWORD}@cluster0.lme5y.mongodb.net/mutual-aid-app?retryWrites=true&w=majority

profile-rest-client:
  url: http://localhost:8200
  password:

logging:
  level:
    root: warn
    org.tms.task_executor_service.domain.service.kafka.consumer.TaskForRetryingListener: warn