server:
  port: 8600

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

application:
  api-info:
    version: 2.0
    title: TASK
    description: Task SERVICE
    contact:
      name: OLEG
      url: https://mail.google.com
      email: vilchinskioleg@gmail.com

feign:
  client:
    config:
      profileRestClient:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
#        requestInterceptors:
#          - com.example.FooRequestInterceptor
  httpclient:
    enabled: true

profile-rest-client:
  user: task-executor-service-client

scheduling-props:
  # period (min) before next scheduled iteration to run TaskExecutionService:
  period: 150
  # how many task to run for one scheduled iteration:
  tasks-amount: 10

kafka:
  bootstrap-servers: localhost:9092
  schema-registry-url: http://localhost:8081