server:
  port: 8100

spring:
  data:
    mongodb:
      database: mutual-aid-app
      uri: mongodb://localhost:27017/mutual-aid-app

application:
  api-info:
    version: 2.0
    title: ORDERS
    description: Order SERVICE
    contact:
      name: OLEG
      url: https://mail.google.com
      email: vilchinskioleg@gmail.com

scheduler:
  remove-closed-orders-job:
    cron: 0 40 14 * * ?
    closed-order-live-hours: 72
    page-size: 10

kafka:
  bootstrapServers: localhost:9092