spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:${MONGO_DB_PASSWORD:test}@cluster0.lme5y.mongodb.net/mutual-aid-app?retryWrites=true&w=majority&appName=Cluster0
      # for connection to local DB. In my case for connection to docker mongoDB container:
      # uri: mongodb://${MONGO_USERNAME}:${MONGO_PWD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=admin

kafka:
  # Within Docker container this property can be overridden by env variable with host alias (instead of localhost),
  # because OS env variables have higher priority for Spring Boot then application props.
  bootstrapServers: 127.0.0.1:9092
  # for SSL security:
  ssl-key-password: 34rtsTb290
  ssl-keystore-location:
  ssl-keystore-password: 34rtsTb290
  ssl-truststore-location:
  ssl-truststore-password: 34rtsTb290

profile-rest-client:
  url: http://localhost:8200
  password: 42vovk_wEle!76

auth-rest-client:
  url: http://localhost:8100
  password: 42vovk_wEle!76