server:
  port: 8100

spring:
  data:
    mongodb:
      # for connection to local DB. In my case for connection to docker mongoDB container:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PWD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=admin

application:
  api-info:
    version: 2.0
    title: ORDERS
    description: Order SERVICE
    contact:
      name: OLEG
      url: https://mail.google.com
      email: vilchinskioleg@gmail.com

feign:
  client:
    config:
      profileRestClient:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
#        requestInterceptors:
#          - com.example.FooRequestInterceptor
  httpclient:
    enabled: true

scheduler:
  remove-closed-orders-job:
    cron: 0 40 14 * * ?
    closed-order-live-hours: 72
    page-size: 10

kafka:
  bootstrapServers: 127.0.0.1:9093
  # for SSL security:
  ssl-key-password: 34rtsTb290
  ssl-keystore-location: /Users/aleh/IdeaProjects/mutual-aid-app-version-2.0-release/order-service/kafka-ssl/secret/clientkeystore.jks
  ssl-keystore-password: 34rtsTb290
  ssl-truststore-location: /Users/aleh/IdeaProjects/mutual-aid-app-version-2.0-release/order-service/kafka-ssl/secret/clienttruststore.jks
  ssl-truststore-password: 34rtsTb290

profile-rest-client:
  url: http://localhost:8400