server:
  port: 8300

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    default-property-inclusion: non_null
    parser:
      allow-comments: true

application:
  api-info:
    version: 2.0
    title: ORDERS
    description: Order SERVICE
    contact:
      name: OLEG
      url: https://mail.google.com
      email: vilchinskioleg@gmail.com

feign:
  client:
    config:
      profileRestClient:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
        requestInterceptors:
          - order.orderservice.configuration.client.profile.ProfileRestClientAuthInterceptor
  httpclient:
    enabled: true

datasource:
  api:
    driver-class-name: org.postgresql.Driver

scheduler:
  remove-closed-orders-job:
    cron: 0 40 14 * * ?
    closed-order-live-hours: 72
    page-size: 10

profile-rest-client:
  user: order-service-client

auth-rest-client:
  user: order-service-client
  read-timeout: 10000
  connection-timeout: 10000