server:
  port: 8100

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:${MONGO_DB_PASSWORD}@cluster0.lme5y.mongodb.net/mutual-aid-app?retryWrites=true&w=majority

application:
  api-info:
    version: 2.0
    title: ORDERS
    description: Order SERVICE
    contact:
      name: OLEG
      url: https://mail.google.com
      email: vilchinskioleg@gmail.com

feign:
  client:
    config:
      profileRestClient:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
        requestInterceptors:
          - order.orderservice.configuration.client.ProfileRestClientAuthInterceptor
  httpclient:
    enabled: true

scheduler:
  remove-closed-orders-job:
    cron: 0 40 14 * * ?
    closed-order-live-hours: 72
    page-size: 10

kafka:
  bootstrapServers: localhost:9092

#rest clients:

profile-rest-client:
  url: http://localhost:8400
  user: order-service-client
  password: 42vovk_wEle!76

auth-rest-client:
  url: http://localhost:8800/api/auth-service
  read-timeout: 10000
  connection-timeout: 10000