server:
  port: 8100

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # use Kafka auto-configuration :
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

application:
  api-info:
    version: 2.0
    title: AUTH
    description: Auth SERVICE
    contact:
      name: OLEG
      url: https://mail.google.com
      email: vilchinskioleg@gmail.com
  kafka:
    topic: mutual-aid-notification-topic