server:
  port: 8100

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

application:
  api-info:
    version: 2.0
    title: AUTH
    description: Auth SERVICE
    contact:
      name: OLEG
      url: https://mail.google.com
      email: vilchinskioleg@gmail.com

feign:
  client:
    config:
      emailSenderApiClient:
        connectTimeout: 10000
        readTimeout: 15000
        loggerLevel: full
        requestInterceptors:
          - org.tms.authservicerest.configuration.client.RapidEmailSenderApiInterceptor

email-sender-open-api:
  url: https://rapidprod-sendgrid-v1.p.rapidapi.com/mail/send
  host: rapidprod-sendgrid-v1.p.rapidapi.com
  token: ${EMAIL_SENDER_API_TOKEN}