server:
  port: 8800

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:${MONGO_DB_PASSWORD}@cluster0.lme5y.mongodb.net/mutual-aid-app?retryWrites=true&w=majority
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

application:
  api-info:
    version: 2.0
    title: AUTH
    description: Auth SERVICE
    contact:
      name: OLEG
      url: https://mail.google.com
      email: vilchinskioleg@gmail.com

auth:
  jwt:
    secret: secret_key
    issuer: auth.service.issuer
    live: 5

feign:
  client:
    config:
      emailSenderApiClient:
        connectTimeout: 10000
        readTimeout: 15000
        loggerLevel: full
        requestInterceptors:
          - org.tms.authservicerest.configuration.client.RapidEmailSenderApiInterceptor

email-sender-open-api:
  url: https://rapidprod-sendgrid-v1.p.rapidapi.com/mail/send
  host: rapidprod-sendgrid-v1.p.rapidapi.com
  token: ${EMAIL_SENDER_API_TOKEN}