spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:${MONGO_DB_PASSWORD}@cluster0.lme5y.mongodb.net/mutual-aid-app?retryWrites=true&w=majority

auth:
  jwt:
    secret: secret_key
    issuer: auth.service.issuer
    live: 5