apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    # Only one node can read/write data at the same time:
    - ReadWriteOnce
  resources:
    requests:
      # Name of reserved piece of HD and amount of HD space:
      storage: 2Gi