apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ssl-broker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kafka-ssl-broker
  template:
    metadata:
      labels:
        component: kafka-ssl-broker
    spec:
      containers:
        - name: kafka-ssl-broker-container
          image:  alehvilchynski/kafka-ssl-broker1
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-cluster-ip:2181
            - name: KAFKA_LISTENERS
              value: SSL://kafka-ssl-broker-cluster-ip:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: SSL://kafka-ssl-broker-cluster-ip:9092
            - name: KAFKA_SECURITY_INTER_BROKER_PROTOCOL
              value: SSL
            - name: SSL_ENABLED_PROTOCOLS
              value: 'TLSv1,TLSv1.1,TLSv1.2,TLSv1.3'
            - name: KAFKA_SSL_CLIENT_AUTH
              value: 'required'
            - name: KAFKA_SSL_KEY_PASSWORD
              value: '34rtsTb290'
            - name: KAFKA_SSL_KEYSTORE_LOCATION
              value: '/serverkeystore.jks'
            - name: KAFKA_SSL_KEYSTORE_PASSWORD
              value: '34rtsTb290'
            - name: KAFKA_SSL_TRUSTSTORE_LOCATION
              value: '/servertruststore.jks'
            - name: KAFKA_SSL_TRUSTSTORE_PASSWORD
              value: '34rtsTb290'