spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:${MONGO_DB_PASSWORD:test}@cluster0.lme5y.mongodb.net/mutual-aid-app?retryWrites=true&w=majority&appName=Cluster0

kafka:
  # Within Docker container this property ('kafka.bootstrapServers') can be overridden by env variable
  # (even without assigning more clear specific key like 'PROPERTY_KEY') with host alias (instead of localhost),
  # because OS env variables have higher priority for Spring Boot then application props (see docker-compose-local.yml).
  bootstrapServers: 127.0.0.1:9092
  listenTopics: mutual-aid-order-topic
  groupId: event-storage-service