server:
  port: 8400

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

application:
  api-info:
    version: 2.0
    title: EVENT STORGE
    description: Event Storage SERVICE
    contact:
      name: OLEG
      url: https://mail.google.com
      email: vilchinskioleg@gmail.com