server:
  port: 8200
  #  address: localhost:8200

spring:
  data:
    mongodb:
      database: mutual-aid-app
      uri: mongodb://localhost:27017/mutual-aid-app

application:
  api-info:
    version: 2.0
    title: EVENT STORGE
    description: Event Storage SERVICE
    contact:
      name: OLEG
      url: https://mail.google.com
      email: vilchinskioleg@gmail.com

kafka:
  bootstrapServers: localhost:9092
  listenTopics: mutual-aid-order-topic
  groupId: event-storage-service