server:
  port: 8200

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:${MONGO_DB_PASSWORD}@cluster0.lme5y.mongodb.net/mutual-aid-app?retryWrites=true&w=majority
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    parser:
      allow-comments: true

application:
  api-info:
    version: 2.0
    title: PROFILE
    description: Profile SERVICE
    contact:
      name: OLEG
      url: https://mail.google.com
      email: vilchinskioleg@gmail.com

feign:
  client:
    config:
      authRestFeignClient:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
        requestInterceptors:
          - org.tms.profile_service_core.configuration.client.auth.AuthRestClientAuthInterceptor

auth-rest-client:
  url: http://localhost:8100
  user: profile-service-rest-client
  password: 423welcome!76
  # for common auth config:
  read-timeout: 15000
  connection-timeout: 10000