spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:${MONGO_DB_PASSWORD:test}@cluster0.lme5y.mongodb.net/mutual-aid-app?retryWrites=true&w=majority&appName=Cluster0

auth-rest-client:
  password: 423welcome!76