server:
  port: 8200

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

application:
  api-info:
    version: 2.0
    title: PROFILE
    description: Profile SERVICE
    contact:
      name: OLEG
      url: https://mail.google.com
      email: vilchinskioleg@gmail.com

feign:
  client:
    config:
      authRestFeignClient:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
        requestInterceptors:
          - org.tms.profile_service_core.configuration.client.auth.AuthRestClientAuthInterceptor
      emailSenderApiClient:
        connectTimeout: 10000
        readTimeout: 15000
        loggerLevel: full
        requestInterceptors:
          - org.tms.profile_service_core.configuration.client.email.RapidEmailSenderApiInterceptor

auth-rest-client:
  user: profile-service-rest-client
  # for common auth config:
  read-timeout: 15000
  connection-timeout: 10000

email-sender-open-api:
  url: https://rapidprod-sendgrid-v1.p.rapidapi.com/mail/send
  host: rapidprod-sendgrid-v1.p.rapidapi.com
  token: ${EMAIL_SENDER_API_TOKEN:test}

kafka:
  bootstrap-servers: localhost:9093
  schema-registry-url: http://localhost:8081
  # SSL security:

enable-task-retry: false