server:
  port: 8200

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

application:
  api-info:
    version: 2.0
    title: PROFILE
    description: Profile SERVICE
    contact:
      name: OLEG
      url: https://mail.google.com
      email: vilchinskioleg@gmail.com

feign:
  client:
    config:
      authRestFeignClient:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
        requestInterceptors:
          - org.tms.profile_service_core.configuration.client.auth.AuthRestClientAuthInterceptor

auth-rest-client:
  user: profile-service-rest-client
  # for common auth config:
  read-timeout: 15000
  connection-timeout: 10000